ZR.UI/Controllers/CustomerNameTitlesController.cs
/************************************************************************************************************
*  COPYRIGHT BY ZIGGY RAFIQ (ZAHEER RAFIQ)
*  LinkedIn Profile URL Address: https://www.linkedin.com/in/ziggyrafiq/ 
*
*  System   :  	ZR Demo Project 04 -  Loyalty Card Scheme
*  Date     :  	5th October 2022
*  Author   :  	Ziggy Rafiq (https://www.ziggyrafiq.com)
*  Notes    :  	
*  Reminder :	PLEASE DO NOT CHANGE OR REMOVE AUTHOR NAME.* 
*  Version  :   0.0.1
************************************************************************************************************/
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Diagnostics;
using ZR.Business.Services.Interfaces;
using ZR.Infrastructure.Models;
using ZR.Infrastructure.ViewModels;
using ZR.UI.Extensions;
using ZR.UI.Models;

namespace ZR.UI.Controllers
{
    
    public class CustomerNameTitlesController : BaseSiteController
    {
        private readonly ILoggerManagerService _logger;

        public CustomerNameTitlesController(ILoggerManagerService loggerManagerService)
        {
            _logger = loggerManagerService;
        }
        public async Task<IActionResult> Index(int? pageNumber, bool? softDeleted)
        {
            _logger.LogError("Testing It.");

            int pageSize = 5;

            if (softDeleted == true)
                return View(await PaginatedList<CustomerTitle>.CreateAsync(Services.Service<ICustomerTileService>().QueryAllCustomersTitlesSoftDeleted(), pageNumber ?? 1, pageSize));

            return View(await PaginatedList<CustomerTitle>.CreateAsync(Services.Service<ICustomerTileService>().QueryAllCustomersTitles(), pageNumber ?? 1, pageSize));
        }

        [HttpGet("CustomerNameTitles/Upsert")]
        public async Task<IActionResult> Upsert(Guid? id)
        {

            if (id == Guid.Empty || id.HasValue == false)
            {

                IEnumerable<SelectListItem> customerNameTitlesList = Services.Service<ICustomerTileService>().GetAllActive()
            .Select(c => new SelectListItem
            {
                Value = c.Id.ToString(),
                Text = c.Name.ToString(),

            });
                ViewBag.CustomerNameTitles = customerNameTitlesList;
                return View();
            }
            else
            {
                ModelState.Clear();
                CustomerVM customerVM = new CustomerVM();
                customerVM.CustomerTitle = await Services.Service<ICustomerTileService>().AsyncGetById(id.Value);

                IEnumerable<SelectListItem> customerNameTitlesList = Services.Service<ICustomerTileService>().GetAllActive()
               .Select(c => new SelectListItem
               {
                   Value = c.Id.ToString(),
                   Text = c.Name.ToString(),
                   Selected = c.Id == customerVM.CustomerTitle.Id ? true : false
               });

                ViewBag.CustomerNameTitles = customerNameTitlesList;

                return View(customerVM);
            }
        }


        [HttpPost("CustomerNameTitles/Upsert")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(CustomerVM customerVM)
        {
            
            if (customerVM.CustomerTitle.Id == Guid.Empty )
            {
                customerVM.CustomerTitle.Id = Guid.NewGuid();
                customerVM.CustomerTitle.IsActive = customerVM.CustomerTitle.IsActive;
                customerVM.CustomerTitle.IsSoftDeleted = customerVM.CustomerTitle.IsSoftDeleted;
                customerVM.CustomerTitle.IsHardDeleted = customerVM.CustomerTitle.IsHardDeleted;

                await Services.Service<ICustomerTileService>().AsyncAdd(customerVM.CustomerTitle);
                return RedirectToAction(nameof(Index));

            }
            else
            {

                await Services.Service<ICustomerTileService>().AsyncUpdate(customerVM.CustomerTitle);

                return RedirectToAction(nameof(Index));
            }

            return View(customerVM);

        }


        [HttpGet("CustomerNameTitles/SoftDelete")]
        public async Task<IActionResult> SoftDelete(Guid id)
        {
            CustomerVM customerVM = new CustomerVM();
            customerVM.CustomerTitle = await Task.Run(() => Services.Service<ICustomerTileService>().AsyncGetById(id));
            
            if (customerVM == null)
            {
                return NotFound();
            }

            return PartialView("SoftDelete", customerVM);

        }


        [HttpPost("CustomerNameTitles/SoftDelete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SoftDeleteConfirmed(CustomerVM customerVM)
        {
                        
            customerVM.CustomerTitle = await Task.Run(() => Services.Service<ICustomerTileService>().AsyncGetById(customerVM.CustomerTitle.Id));

            await Services.Service<ICustomerTileService>().AsyncSoftDelete(customerVM.CustomerTitle.Id);

            return RedirectToAction("Index");

        }


        [HttpGet("CustomerNameTitles/HardDelete")]
        public async Task<IActionResult> HardDelete(Guid id)
        {
            CustomerVM customerVM = new CustomerVM();
            customerVM.CustomerTitle = await Task.Run(() => Services.Service<ICustomerTileService>().AsyncGetById(id));
            if (customerVM.CustomerTitle == null)
            {
                return NotFound();
            }

            return PartialView("HardDelete", customerVM);
        }


        [HttpPost("CustomerNameTitles/HardDelete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> HardDeleteConfirmed(CustomerVM customerVM)
        {
            
            customerVM.CustomerTitle = await Task.Run(() => Services.Service<ICustomerTileService>().AsyncGetById(customerVM.CustomerTitle.Id));
            
            await Services.Service<ICustomerTileService>().AsyncDelete(customerVM.CustomerTitle.Id);
            return RedirectToAction("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ZR.UI/Views/Shared/_Layout.cshtml
@*/************************************************************************************************************
*  COPYRIGHT BY ZIGGY RAFIQ (ZAHEER RAFIQ)
*  LinkedIn Profile URL Address: https://www.linkedin.com/in/ziggyrafiq/
*
*  System   :  	ZR Demo Project 04 -  Loyalty Card Scheme
*  Date     :  	5th October 2022
*  Author   :  	Ziggy Rafiq (https://www.ziggyrafiq.com)
*  Notes    :
*  Reminder :	PLEASE DO NOT CHANGE OR REMOVE AUTHOR NAME.
*  Version  :   0.0.1
************************************************************************************************************/*@
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ziggy Rafiq Demo Project 04</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script src="https://kit.fontawesome.com/bde21d3af6.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ZR.UI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Ziggy Rafiq Demo 04</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item text-center">
                            <i class="fas fa-users"></i>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Customers</a>
                        </li>
                        
                        <li class="nav-item text-center">
                            <i class="fas fa-pencil-ruler"></i>
                            <a class="nav-link text-dark" asp-area="" asp-controller="CustomerNameTitles" asp-action="Index">Customer Name Titles</a>
                        </li>
                        <li class="nav-item text-center">
                            <i class="fas fa-user-secret"></i>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ZR.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>